name: Scala CI

on:
  push:
    branches: [  ci_testing  ]
  pull_request:
    branches: [  ci_testing  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ViperServer
      uses: actions/checkout@v2
      with:
        path: viperServer
    - name: Checkout Silver
      uses: actions/checkout@v2
      with:
        repository: WissenIstNacht/Silver
        path: silver
    - name: Checkout Silicon
      uses: actions/checkout@v2
      with:
        repository: WissenIstNacht/Silicon
        path: silicon
    - name: Checkout Carbon
      uses: actions/checkout@v2
      with:
        repository: WissenIstNacht/Carbon
        path: carbon    
#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Run Compilation  
#       run: sbt assembly
#     - name: Run Tests
#       run: sbt test
    - name: print directory
      run: pwd > print_dir.txt | ls >> print_dir.txt | cat print_dir.txt
    - name: Upload directory content printout
      uses: actions/upload-artifact@v2
      with:
        name: directory_content_printout
        path: ${{ github.workspace }}/print_dir.txt
